pipeline {
    agent any
    environment {
        DOCKERHUB_LOGIN = credentials('dockerhub-login')
    }
    stages {
        stage('Download Artifactory') {
            steps {
                rtDownload (
                    serverId:"ArtifactoryJfrog",
                    spec: '''{
                         "files": [
                             {
                                 "pattern": "spring-calculator",
                                 "target": "./"
                             }
                         ]
                    }''',
                )
            }
        }
        stage('Build Docker Image and Publish on Dockerhub') {
            steps {
                sh "packer build -var 'dockerhub_username=$DOCKERHUB_LOGIN_USR' -var 'dockerhub_password=$DOCKERHUB_LOGIN_PSW' infra/job2/packer_template.json"
            }
        }
    }
}