pipeline {
    agent any

    stages {
        stage('Download Artifactory') {
            steps {
                rtDownload (
                    serverId:"ArtifactoryJfrog",
                    spec: '''{
                         "files": [
                             {
                                 "pattern": "spring-calculator",
                                 "target": "./"
                             }
                         ]
                    }''',
                )
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "packer build ./packer_template.json"
            }
        }
    }
}