pipeline {
    agent any

    stages {
        stage('Preparation') {
            steps {
                git 'https://github.com/ViniLemess/SpringCalculator.git'
            }
        }
        stage('Test') {
            steps {
                sh "./gradlew test"
            }
        }
        stage('Build') {
            steps {
                sh "./gradlew clean build"
            }
        }
        stage('Upload Artifactory') {
            steps {
                rtUpload (
                    serverId:"ArtifactoryJfrog",
                     spec: '''{
                         "files": [
                             {
                                 "pattern": "build/libs/*.jar",
                                 "target": "spring-calculator"
                             }
                         ]
                     }''',
                )
            }
        }
        stage('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "ArtifactoryJfrog"
                )
            }
        }
    }
}